name: QA

on:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load environment
        run: |
          grep -v '^#' metadata.env >> $GITHUB_ENV

      - name: Test image build
        uses: docker/bake-action@v6
        with:
          targets: build
